'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

Public MustInherit Class BaseTransactionService
    Inherits System.Web.Services.WebService

    Public MustOverride Function requestTransaction(ByVal userId As String, ByVal passwd As String, ByVal userTransactionId As String, ByVal srsRatingId As Long, ByVal msisdn As String, ByVal contentId As String, ByVal contentName As String, ByVal urlOk As String, ByVal urlCancel As String, ByVal urlError As String, ByVal urlUnsusc As String, ByVal extraParam As String) As <System.Xml.Serialization.SoapElementAttribute("requestTransactionReturn")> String
    Public MustOverride Function requestTransactionInt(ByVal userId As String, ByVal passwd As String, ByVal userTransactionId As String, ByVal srsRatingId As String, ByVal msisdn As String, ByVal contentId As String, ByVal contentName As String, ByVal urlOk As String, ByVal urlCancel As String, ByVal urlError As String, ByVal urlUnsusc As String, ByVal extraParam As String) As <System.Xml.Serialization.SoapElementAttribute("requestTransactionIntReturn")> String
    Public MustOverride Function getStatus(ByVal userId As String, ByVal passwd As String, ByVal transactionId As String) As <System.Xml.Serialization.SoapElementAttribute("getStatusReturn")> String

End Class
