'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.4927.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "1.0.3705.0"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="FavoritesSoapBinding", [Namespace]:="http://189.254.103.147:8088/sia/services/Favorites")>  _
Partial Public Class FavoritesService
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    '''<remarks/>
    Public Sub New(ByVal url As String)
        MyBase.New()
        'Me.Url = "http://189.254.103.147:8088/sia/services/Favorites"
        Me.Url = url
    End Sub
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://webservice.sia.sm.com", ResponseNamespace:="http://189.254.103.147:8088/sia/services/Favorites")>  _
    Public Function askFav(ByVal userId As String, ByVal passwd As String, ByVal msisdn As String, ByVal url As String, ByVal title As String) As <System.Xml.Serialization.SoapElementAttribute("askFavReturn")> String
        Dim results() As Object = Me.Invoke("askFav", New Object() {userId, passwd, msisdn, url, title})
        Return CType(results(0),String)
    End Function
    
    '''<remarks/>
    Public Function BeginaskFav(ByVal userId As String, ByVal passwd As String, ByVal msisdn As String, ByVal url As String, ByVal title As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("askFav", New Object() {userId, passwd, msisdn, url, title}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Function EndaskFav(ByVal asyncResult As System.IAsyncResult) As String
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),String)
    End Function
End Class
