'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.4927.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "1.0.3705.0"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="TariffSoapBinding", [Namespace]:="http://189.254.103.147:8088/sia/services/Tariff")>  _
Partial Public Class TariffService
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    '''<remarks/>
    Public Sub New(ByVal url As String)
        MyBase.New()
        'Me.Url = "http://189.254.103.147:8088/sia/services/Tariff"
        Me.Url = Url
    End Sub
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://webservice.sia.sm.com", ResponseNamespace:="http://189.254.103.147:8088/sia/services/Tariff")>  _
    Public Function getTariff(ByVal userId As String, ByVal passwd As String, ByVal srsRatingId As Long) As <System.Xml.Serialization.SoapElementAttribute("getTariffReturn")> String
        Dim results() As Object = Me.Invoke("getTariff", New Object() {userId, passwd, srsRatingId})
        Return CType(results(0),String)
    End Function
    
    '''<remarks/>
    Public Function BegingetTariff(ByVal userId As String, ByVal passwd As String, ByVal srsRatingId As Long, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getTariff", New Object() {userId, passwd, srsRatingId}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Function EndgetTariff(ByVal asyncResult As System.IAsyncResult) As String
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),String)
    End Function
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://webservice.sia.sm.com", ResponseNamespace:="http://189.254.103.147:8088/sia/services/Tariff")>  _
    Public Function getTariffInt(ByVal userId As String, ByVal passwd As String, ByVal srsRatingId As Integer) As <System.Xml.Serialization.SoapElementAttribute("getTariffIntReturn")> String
        Dim results() As Object = Me.Invoke("getTariffInt", New Object() {userId, passwd, srsRatingId})
        Return CType(results(0),String)
    End Function
    
    '''<remarks/>
    Public Function BegingetTariffInt(ByVal userId As String, ByVal passwd As String, ByVal srsRatingId As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getTariffInt", New Object() {userId, passwd, srsRatingId}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Function EndgetTariffInt(ByVal asyncResult As System.IAsyncResult) As String
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),String)
    End Function
End Class
