'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.4927.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "1.0.3705.0"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="TransactionSoapBinding", [Namespace]:="http://192.168.1.120:8088/sia/services/Transaction")>  _
Partial Public Class TransactionService
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    '''<remarks/>
    Public Sub New(ByVal url As String)
        MyBase.New()
        'Me.Url = "http://189.254.103.147:8088/sia/services/Transaction"
        Me.Url = Url
    End Sub
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapRpcMethodAttribute(RequestNamespace:="http://webservice.sia.sm.com", ResponseNamespace:="http://192.168.1.120:8088/sia/services/Transaction")> _
    Public Function requestTransaction(ByVal userId As String, ByVal passwd As String, ByVal userTransactionId As String, ByVal srsRatingId As Long, ByVal msisdn As String, ByVal contentId As String, ByVal contentName As String, ByVal urlOk As String, ByVal urlCancel As String, ByVal urlError As String, ByVal urlUnsusc As String, ByVal extraParam As String) As <System.Xml.Serialization.SoapElementAttribute("requestTransactionReturn")> String
        Dim results() As Object = Me.Invoke("requestTransaction", New Object() {userId, passwd, userTransactionId, srsRatingId, msisdn, contentId, contentName, urlOk, urlCancel, urlError, urlUnsusc, extraParam})
        Return CType(results(0), String)
    End Function
    
    '''<remarks/>
    Public Function BeginrequestTransaction(ByVal userId As String, ByVal passwd As String, ByVal userTransactionId As String, ByVal srsRatingId As Long, ByVal msisdn As String, ByVal contentId As String, ByVal contentName As String, ByVal urlOk As String, ByVal urlCancel As String, ByVal urlError As String, ByVal urlUnsusc As String, ByVal extraParam As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("requestTransaction", New Object() {userId, passwd, userTransactionId, srsRatingId, msisdn, contentId, contentName, urlOk, urlCancel, urlError, urlUnsusc, extraParam}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Function EndrequestTransaction(ByVal asyncResult As System.IAsyncResult) As String
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),String)
    End Function
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapRpcMethodAttribute(RequestNamespace:="http://webservice.sia.sm.com", ResponseNamespace:="http://192.168.1.120:8088/sia/services/Transaction")> _
    Public Function requestTransactionInt(ByVal userId As String, ByVal passwd As String, ByVal userTransactionId As String, ByVal srsRatingId As String, ByVal msisdn As String, ByVal contentId As String, ByVal contentName As String, ByVal urlOk As String, ByVal urlCancel As String, ByVal urlError As String, ByVal urlUnsusc As String, ByVal extraParam As String) As <System.Xml.Serialization.SoapElementAttribute("requestTransactionIntReturn")> String
        Dim results() As Object = Me.Invoke("requestTransactionInt", New Object() {userId, passwd, userTransactionId, srsRatingId, msisdn, contentId, contentName, urlOk, urlCancel, urlError, urlUnsusc, extraParam})
        Return CType(results(0), String)
    End Function
    
    '''<remarks/>
    Public Function BeginrequestTransactionInt(ByVal userId As String, ByVal passwd As String, ByVal userTransactionId As String, ByVal srsRatingId As String, ByVal msisdn As String, ByVal contentId As String, ByVal contentName As String, ByVal urlOk As String, ByVal urlCancel As String, ByVal urlError As String, ByVal urlUnsusc As String, ByVal extraParam As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("requestTransactionInt", New Object() {userId, passwd, userTransactionId, srsRatingId, msisdn, contentId, contentName, urlOk, urlCancel, urlError, urlUnsusc, extraParam}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Function EndrequestTransactionInt(ByVal asyncResult As System.IAsyncResult) As String
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),String)
    End Function
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapRpcMethodAttribute(RequestNamespace:="http://webservice.sia.sm.com", ResponseNamespace:="http://192.168.1.120:8088/sia/services/Transaction")> _
    Public Function getStatus(ByVal userId As String, ByVal passwd As String, ByVal transactionId As String) As <System.Xml.Serialization.SoapElementAttribute("getStatusReturn")> String
        Dim results() As Object = Me.Invoke("getStatus", New Object() {userId, passwd, transactionId})
        Return CType(results(0), String)
    End Function
    
    '''<remarks/>
    Public Function BegingetStatus(ByVal userId As String, ByVal passwd As String, ByVal transactionId As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getStatus", New Object() {userId, passwd, transactionId}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Function EndgetStatus(ByVal asyncResult As System.IAsyncResult) As String
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),String)
    End Function
End Class
