'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.4927.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "1.0.3705.0"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="UserSoapBinding", [Namespace]:="http://192.168.1.120:8088/sia/services/User")>  _
Partial Public Class UserService
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    '''<remarks/>
    Public Sub New()
        MyBase.New
        Me.Url = "http://189.254.103.147:8088/sia/services/User"
    End Sub
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://webservice.sia.sm.com", ResponseNamespace:="http://192.168.1.120:8088/sia/services/User")>  _
    Public Function getMSISDN(ByVal userId As String, ByVal passwd As String, ByVal imsi As String) As <System.Xml.Serialization.SoapElementAttribute("getMSISDNReturn")> String
        Dim results() As Object = Me.Invoke("getMSISDN", New Object() {userId, passwd, imsi})
        Return CType(results(0),String)
    End Function
    
    '''<remarks/>
    Public Function BegingetMSISDN(ByVal userId As String, ByVal passwd As String, ByVal imsi As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getMSISDN", New Object() {userId, passwd, imsi}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Function EndgetMSISDN(ByVal asyncResult As System.IAsyncResult) As String
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),String)
    End Function
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://webservice.sia.sm.com", ResponseNamespace:="http://192.168.1.120:8088/sia/services/User")>  _
    Public Function getProfile(ByVal userId As String, ByVal passwd As String, ByVal msisdn As String) As <System.Xml.Serialization.SoapElementAttribute("getProfileReturn")> String
        Dim results() As Object = Me.Invoke("getProfile", New Object() {userId, passwd, msisdn})
        Return CType(results(0),String)
    End Function
    
    '''<remarks/>
    Public Function BegingetProfile(ByVal userId As String, ByVal passwd As String, ByVal msisdn As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("getProfile", New Object() {userId, passwd, msisdn}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Function EndgetProfile(ByVal asyncResult As System.IAsyncResult) As String
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),String)
    End Function
End Class
